### ISSUE TITLE
如果能支持拉箭头的话就完美了

### ISSUE THREAD

**Issue by Roc0323** [jenly1314/DrawBoard#1]
如果能支持拉箭头的话就完美了

**Comment by jenly1314** [comment]
**DrawBoard** 本身已提供动态添加自定义实现的 **Draw** ，这个你只需参照： **DrawLine** 的实现自定义实现一个 **Draw** ，然后添加到**DrawMap** 中即可实现了。

**Comment by Roc0323** [comment]
好的，我试试



在 2022-07-21 14:25:47，"Jenly" ***@***.***> 写道：

DrawBoard 本身已提供动态添加自定义实现的 Draw ，这个你只需参照： DrawLine 的实现自定义实现一个 Draw ，然后添加到DrawMap 中即可实现了。
